### ISSUE TITLE
Pico and Ports ROMS missing

### ISSUE THREAD

**Issue by umartoot** [cbepx-me/Anbernic-H700-RG-xx-StockOS-Modification#13]
Games added to the os generated folders for pico and ports do not show up in Game Room or Retroarch.

As a test I added roms for GBA, Pico, and Ports in their respective folders. Opening up RA Game only shows GBA. 

I did have success starting retroarch, loading fake-8 core, navigating the folders to a pico8 game and loading the content to run a game.

**Comment by Gabi-90** [comment]
@umartoot The pico8 games must be in .p8 format and the ports each come with a folder accompanied by a .sh file, copy the files into their respective folders and they should work for you, maybe you are doing something wrong, all of this works perfectly for me.
