### ISSUE TITLE
NTP and SSH functionality?

### ISSUE THREAD

**Issue by seth-rasmussen** [cbepx-me/Anbernic-H700-RG-xx-StockOS-Modification#18]
No documentation or instructions on enabling (disabled by default according to docs) the ssh or ntp functions in this OS... Been through multiple menus and options and can not find where or how to turn on.

**Comment by SneakyTwitch** [comment]
seems like you didnt go through enough menus then. It is located in RA> Apps . Find it in the TF card you install the OS in. 

the script name
1. Network_Time_protocol-(on/off)
2. SSH_Server-(on/off)

**Comment by seth-rasmussen** [comment]
For reference, everything should have installed correctly. Downloaded from here: https://drive.google.com/drive/folders/1uwCkGX3H-K09pj0VbB6hkS8I0_qhzrGY?usp=sharing
Then unzipped, went to RG35XX_PLUS_&_RG35XX_2024 >Stock_OS_MOD>OS_Image and unzipped the image there. I then flashed it using Balena plugged it in tf1 put a new card in tf2 and powered on. Firmware version is showing: RG35xx+_P_2-240409

**Comment by SneakyTwitch** [comment]
https://drive.google.com/file/d/1PxOsCLlDlntxEuizJ5zbwJ6emqh2J75b/view?usp=sharing

Here you go. These are pulled from my 35xxH . You can try.

**Comment by ahmed2m** [comment]
> Then unzipped, went to RG35XX_PLUS_&_RG35XX_2024 >Stock_OS_MOD>OS_Image and unzipped the image there. I then flashed it using Balena plugged it in tf1 put a new card in tf2 and powered on. Firmware version is showing: RG35xx+_P_2-240409

Happened to me as well on my xxH. I did exactly like you, maybe the problem, for some reason, is booting the first time with both tf1, tf2 on?
I will try again later if I have time.

**Comment by SneakyTwitch** [comment]
For first time boot, clean setup, just use TF1 only. 
After 1st installation, if there are nothing in the Apps section. Use Tripartition wizard, you can expand the rightmost TF1 space into Fat32, name it ROMS.  It works in any size SDCard. 
Put it back , turn it on, and let it copy the files (Apps and others) over to TF1 

Afterwards. you can plug in any Fat32 TF2, and it will setup the required directory folders (Roms and others) 
Unplug TF2, and transfer your games in.

**Comment by ahmed2m** [comment]
Okay so the expanding is the missing step?
I had the idea that (automatically created) roms parition expansion step is optional. 

Btw I see "copying files..." on **every** boot, is that also related to the whole thing? Or is that normal.

**Comment by SneakyTwitch** [comment]
If its "copying files..."  on every boot, It usually only happen on the 1st two boots (Tf1, and Tf1 after expanding) might means that there is issue in copying the files over. You might want to re-flash the sdcard.

**Comment by ahmed2m** [comment]
Done that and everything worked great, however I also did as #6 said, apparently flashing using balena etcher on MacOS doesn't format the card as GUID so the partitioning was just messed up. I removed the dust off my windows laptop and did everything on Rufus.

**Comment by cbepx-me** [comment]
Judging from the current feedback, this problem occurs because of the use of balena flash tf1 on macos. Please use rufus under windows to complete the operation.

**Comment by Skeeve** [comment]
> Judging from the current feedback, this problem occurs because of the use of balena flash tf1 on macos. Please use rufus under windows to complete the operation.

For me `dd` worked fine on Mac. I have no WinDOS.
