### ISSUE TITLE
[Bug] The controls don't work in some games on ps1

### ISSUE THREAD

**Issue by Crypt0null** [cbepx-me/Anbernic-H700-RG-xx-StockOS-Modification#38]
The controls don't work in some games on ps1(example ff7, chrono trigger). I have to change the core on swanstation
Checked the same roms on stock there are no problems there on same core

edit: There is a way to fix it. go to Main Menu -> Quick Menu -> Controls -> Port 1 Controls -> Device Type and select standart instead of dualshock.
On ofw dualshock is also standard setting and there is no problem there so still need a fix

**Comment by Crypt0null** [comment]
My model RG35XX H if this is important for dev. Maybe other models don't have this problem

**Comment by anilkusaksiz** [comment]
I have the same issue on Disney's Hercules. Controls work for a few seconds, then I see a message inside the game like "Please insert a controller into port 1".
When I switch the device type dualshock or standard, again it works for a few seconds then stop working again. 
Device is RG35XX H

**Comment by Crypt0null** [comment]
Thanks @cbepx-me for updating the mod so quickly!
 But I checked both version 2.4 and the new 2.5 and unfortunately the control bug on ps1 is still there
 Switching to "standard" mode is the only solution. When switching to "dualshock", the control is lost after a couple of seconds

**Comment by cbepx-me** [comment]
This is not a bug, it occurs because of a problem with PSX games being compatible with its various controller types, and switching between "standard" and "dualshock" modes is the only way to fix it.
