### ISSUE TITLE
Request for Drastic Build by steward-fu, bring various layouts for NDS

### ISSUE THREAD

**Issue by hva314** [cbepx-me/Anbernic-H700-RG-xx-StockOS-Modification#44]
Hello dev,

First, I would like to thank you for this amazing Firmware.
I would like to request for a feature - the Drastic Emulator by steward-fu. The build is originally for Miyoo Mini, brings various different styles of layout for NDS, which enhance the experience of NDS game on Miyoo and RG35XX screen size. 
Recently, there has been a port of this Drastic build for RG35XX Plus/H on MuOS and Batocera at https://github.com/trngaje/rg35xxh_binary. 
I would like to request your help brining this build to this firmware.

**Comment by cbepx-me** [comment]
I have already forwarded your request to anbernic
