### ISSUE TITLE
Backup/Restore Script

### ISSUE THREAD

**Issue by MoeFoh** [cbepx-me/Anbernic-H700-RG-xx-StockOS-Modification#54]
Latest 0618 fw (latest) - 35xx-2024.
Key A = Restore ?
Key Y = Backup ?

Picture shows the opposite.

**Comment by TheKerevas** [comment]
I confirm that the keys do not match the image on the screen

**Comment by cbepx-me** [comment]
This issue does exist and will be fixed in the next version. Thank you
