### ISSUE TITLE
There is no way to exit the emulator core selection menu for the game

### ISSUE THREAD

**Issue by DV8ZXPru** [cbepx-me/Anbernic-H700-RG-xx-StockOS-Modification#60]
If you press Y and enter the core selection menu for the game (for any console), then press F and enter the settings menu, then exit the settings menu back to the kernel selection menu with the B key, then it will be impossible to exit the core selection menu. Only by turning off the device

I don’t know which firmware this bug was originally in, stock or modified, since I noticed it only on the modified one
Device Model: RG35xx+_P
OS Date: 20240428
Mod Ver: 2.4

**Comment by Skeeve** [comment]
Confirmed for V1.1.3 with mod 2.5
