### ISSUE TITLE
Can't save control/input remap override for arcade emulators in RA

### ISSUE THREAD

**Issue by Senkudou** [cbepx-me/Anbernic-H700-RG-xx-StockOS-Modification#61]
For the RG28XX, every time I try to save an input remap override for any of the arcade emulators, it never actually saves. When I quit and launch the game (after saving overrides) it instead launches the game back to its original mapping. I don't know if this is an issue with the stock or mod but this started happening after I updated to the latest firmware

EDIT:
Okay so further testing, this seems to be an issue with the latest stock firmware on the RG35XX H but not the RG28XX. So Anbernic must've added some sort of script to autocreate an input remap when an arcade game is launched. Thus whenever you try to make your own remap, it'll be overwritten by the OS on the next launch. 

EDIT 2:
I managed to get around this by simply changing the location of where the remap files are saved in RetroArch.

So create a new folder (I made on SD2 as "Remaps"). Go into the RetroArch program via Settings > Retroarch Settings > Start Retroarch > Yes

Then once RetroArch opens go to Settings > Directory > Input Remaps > Select your new folder

Be sure to save your configuration before exiting out of RetroArch.

**Comment by cbepx-me** [comment]
I want to know what changes have been made in your remapping?

**Comment by Senkudou** [comment]
> I want to know what changes have been made in your remapping?

So the default is L1 is heavy punch, and R1 is heavy kick. I like to make so that L1 does nothing, and R1 is heavy punch, while R2 is heavy kick. Everytime I save the new layout, be it save it for the game or core, it always goes back the to the default mapping when launching the game. The game I'm testing out is Street Fighter III: 3rd Strike using FB Neo

I should mention that the latest stock OS of RG28XX has this happening as well. So it seems to be something that the stock OS is doing and not the modded version like I initially thought. My bad on that.

**Comment by Senkudou** [comment]
Okay sorry for posting back to back but I managed to get around this by simply changing the location of where the remap files are saved in RetroArch:

So create a new folder (I made on SD2 as "Remaps"). Go into the RetroArch program via Settings > Retroarch Settings > Start Retroarch > Yes

Then once RetroArch opens go to Settings > Directory > Input Remaps > Select your new folder

Be sure to save your configuration before exiting out of RetroArch.
