### ISSUE TITLE
RG35XX SP, 1.0.7, Power Indicator

### ISSUE THREAD

**Issue by Johny-LPM** [cbepx-me/Anbernic-H700-RG-xx-StockOS-Modification#79]
I can't vouch for whether this is an issue coming from the Stock OS already or something with this Modded image, but I haven't really seen other people complain about so I figured I might as well mention it in case I might've done something wrong.

The issue in question is related to the power indicator/percentage. 
It seems as though any time I make use of the deep sleep mode, it gets messed up and even the LED turns red as if it were really the case that it's low on battery. 
Simply popping out the battery compartment and plugging out and back in seems to fix the issue, but I'd be remiss if I said it's fine to carry a screwdriver everywhere and do it whenever this happens.

This only seems to happen whenever I make use of the deep sleep and nothing of the sort happens with Knulli/MuOS, but they do also display incorrect battery % whenever this happens.

Again, I'm not sure if this is a problem with upstream. I've seen both MuOS and Knulli people mention how this deep sleep solution of Anbernic's in the Stock OS is far from ideal and hence why they're waiting for the mainline kernel. 
But like I said, other people don't seem to be complaining about it and there is a larger amount of Stock users. 
So either it's really something on my end or with this Modded version.

Either way, if need be, I'll download the godforsaken 64GB image and wait a million years for it to flash in order to properly test this with Stock, but I figured I might as well leave an issue up in case it happens to someone else.

I'll close this by thanking @cbepx-me for this project and for their work on this, it's really awesome!

**Comment by cbepx-me** [comment]
This situation did not occur in the stock and mod versions of the test, and the specific reason cannot be determined

**Comment by Johny-LPM** [comment]
Very well, I must've been something on my end with Stock mod specifically. Carry on!
